-- 記事URLを数字にする（/articles/1, /articles/2 ...）
-- 既存の行にも自動で番号が振られる
ALTER TABLE articles ADD COLUMN IF NOT EXISTS number bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS articles_number_key ON articles (number);
